version: "3.0"
services:
  kinetic:
    build: 
      context: docker
      dockerfile: Dockerfile
      network: host
    container_name: ros_vnc
    image: ros_vnc:kinetic
    volumes:
      - $PWD/workspace:/home/ubuntu/workspace
    ports:
      - 40080:80
      - 45901:5901
